Implement exactly what Alex and I discussed.
When encoding a module with dupes, this happens:
```
error: failed to encode a component from module

Caused by:
    0: failed to decode world from module
    1: module was not valid
    2: module has duplicate import for `wasi_snapshot_preview1::proc_exit`
```