WIP. Insert deduped import names in validator.  However, I still haven't got encoding right.
* Add trace messages about when things are pushed onto `exports` so I can see whether deduplicated names make it on.

Now it says this:
```
error: failed to encode a component from module

Caused by:
    0: failed to decode world from module
    1: failed to validate the imports of the adapter module `wasi_snapshot_preview1`
    2: adapter module did not export `proc_exit_0`
```