Make the validator tolerate duplicate imports by skipping them.
Now we get…
```
error: failed to encode a component from module

Caused by:
    0: failed to validate component output
    1: module has a duplicate import name `wasi_snapshot_preview1:proc_exit` that is not allowed in components (at offset 0x24c)
```