(to squash) Fix validation errors where we were complaining that `fd_write_0` (and other such renames of duplicate imports) couldn't be found in the module we were importing from.
Of course they couldn't. We'll ignore that during validation and then stitch it up later.

For example:
```
RUST_BACKTRACE=1 target/debug/wasm-tools component new minimal.wat -o minimal-dupes.wasm --adapt wasi_snapshot_preview1.wasm
error: failed to encode a component from module

Caused by:
    0: failed to decode world from module
    1: failed to validate the imports of the adapter module `wasi_snapshot_preview1`
    2: adapter module did not export `proc_exit_0`
```

Also make `IndexMap.deduplications` contain only duplicates. Factor up the concept of `contains()` to DRY lookup, which now has to check both there and `IndexMap.names`. Make `deduplicate_name` responsible for writing to `deduplications`.